### ISSUE TITLE
String variables in symbol table

### ISSUE THREAD

**Issue by dlorych** [mjdrushton/cexprtk#6]
Does cexprtk and/or exprtk support string variables in symbol table?

I tried to run following code, but I'm getting `TypeError: must be real_number, not str`

```python
import cexprtk
cexprtk.evaluate_expression("if (x == 'one') 1; else 10;", {"x": 'one'})
```

Comparing string values directly works as expected
```python
import cexprtk
cexprtk.evaluate_expression("if ('one' == 'one') 1; else 10;", {})
```

**Comment by dlorych** [comment]
ExprTK seems to support that. `exprtk::symbol_table_t` has a method `add_stringvar`. It seems to be a matter of adding support in cexprtk.

I could try adding it, but I'm not familiar with Python bindings. Any guidance on that?

**Comment by mjdrushton** [comment]
It looks doable - I'll try to add it in the next few days.

**Comment by mjdrushton** [comment]
I have added support for string variables.

Your example needs to be written like this:

`import cexprtk
st = cexprtk.Symbol_Table({}, string_variables={"x": "one"})
expression = cexprtk.Expression("if (x == 'one') 1; else 10;", st)
expression.value()
`
