### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by MK096** [mjdrushton/cexprtk#9]
While running the exe file on a different machine i get DLL load failed error.
Few weeks before it used to work fine. I tried reinstalling the package and even tried different versions of it.

This is the command i use to generate exe:
python -m eel filename.py Compiled --hidden-import=cexprtk._functionargs --onefile

eel is a package to integrate HTML UI with python.

I have win 10 64 bit sy
![cexprtk](https://user-images.githubusercontent.com/20142735/158944298-ac206c4c-b84f-4bcc-b3a4-2be8156fae5c.png)
s

**Comment by mjdrushton** [comment]
What was the version you were using when it worked?
At what version did things stop working for you?
What version of python are you using?

Does your program work if you don't try to use it through eel? (i.e. is this actually a cexprtk problem or a packaging problem?)

**Comment by mjdrushton** [comment]
Problem appears to be with use of eel and not with cexprtk. Unable to replicate.
